SELECT
    cohort_group AS cohort,
    COUNT(DISTINCT(user_email)) AS cohort_size,
    SUM(net_revenue) AS cohort_clv,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 0) / SUM(net_revenue), 4), 0) AS m0,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 1) / SUM(net_revenue), 4), 0) AS m1,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 2) / SUM(net_revenue), 4), 0) AS m2,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 3) / SUM(net_revenue), 4), 0) AS m3,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 4) / SUM(net_revenue), 4), 0) AS m4,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 5) / SUM(net_revenue), 4), 0) AS m5,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 6) / SUM(net_revenue), 4), 0) AS m6,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 7) / SUM(net_revenue), 4), 0) AS m7,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 8) / SUM(net_revenue), 4), 0) AS m8,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 9) / SUM(net_revenue), 4), 0) AS m9,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 10) / SUM(net_revenue), 4), 0) AS m10,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 11) / SUM(net_revenue), 4), 0) AS m11,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 12) / SUM(net_revenue), 4), 0) AS m12,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 13) / SUM(net_revenue), 4), 0) AS m13,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 14) / SUM(net_revenue), 4), 0) AS m14,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 15) / SUM(net_revenue), 4), 0) AS m15,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 16) / SUM(net_revenue), 4), 0) AS m16,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 17) / SUM(net_revenue), 4), 0) AS m17,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 18) / SUM(net_revenue), 4), 0) AS m18,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 19) / SUM(net_revenue), 4), 0) AS m19,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 20) / SUM(net_revenue), 4), 0) AS m20,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 21) / SUM(net_revenue), 4), 0) AS m21,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 22) / SUM(net_revenue), 4), 0) AS m22,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 23) / SUM(net_revenue), 4), 0) AS m23,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 24) / SUM(net_revenue), 4), 0) AS m24,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 25) / SUM(net_revenue), 4), 0) AS m25,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 26) / SUM(net_revenue), 4), 0) AS m26,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 27) / SUM(net_revenue), 4), 0) AS m27,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 28) / SUM(net_revenue), 4), 0) AS m28,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 29) / SUM(net_revenue), 4), 0) AS m29,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 30) / SUM(net_revenue), 4), 0) AS m30,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 31) / SUM(net_revenue), 4), 0) AS m31,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 32) / SUM(net_revenue), 4), 0) AS m32,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 33) / SUM(net_revenue), 4), 0) AS m33,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 34) / SUM(net_revenue), 4), 0) AS m34,
    COALESCE(ROUND(SUM(net_revenue) FILTER (WHERE months_since_first_purchase = 35) / SUM(net_revenue), 4), 0) AS m35
FROM cohort_analysis_data
GROUP BY 1
ORDER BY 1;
